export default [
    {
        title: "A Farewell to Arms",
        releaseYear: 1932,
        genreId: 1,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/A_Farewell_to_Arms%201932.jpg?alt=media&token=91ac6c48-7186-410c-b30d-67f5bf502632",
        source: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/farewell_to_arms_512kb.mp4?alt=media&token=91e3657d-1fe2-42bb-af23-b9c439bcd54b",
        des: "Based on the 1929 semi-autobiographical novel A Farewell to Arms by Ernest Hemingway, with a screenplay by Oliver H.P. Garrett and Benjamin Glazer, the film is about a romantic love affair between an American ambulance driver and an English nurse in Italy during World War I. The film received Academy Awards for Best Cinematography and Best Sound, and was nominated for Best Picture and Best Art Direction.",
    },
    {
        title: "Africa Speaks",
        releaseYear: 1930,
        genreId: 2,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Africa_Speaks%201930.jpg?alt=media&token=62d37105-ea4d-4457-873b-d66d62b751a0",
        source: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/farewell_to_arms_512kb.mp4?alt=media&token=91e3657d-1fe2-42bb-af23-b9c439bcd54b",
        des: "Directed by Walter Futter and narrated by Lowell Thomas.",
    },
    {
        title: "Alice in Wonderland",
        releaseYear: 1915,
        genreId: 3,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Alice_in_Wonderland%201915.jpg?alt=media&token=2de1f8ca-006a-45b5-9516-a51638d3bf2b",
        source: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/AliceInWonderland-WithAudio_512kb.mp4?alt=media&token=85a7c62d-e82c-494e-9bb7-24f004d9a488",
        des: "This film version is notable for depicting the 'You Are Old, Father William in its entirety and it includes an image of John Tenniel's illustration of Father William doing his back-somersault at the front door.",
    },
    {
        title: "Big Chance",
        releaseYear: 1933,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Big_Chance%201933.jpg?alt=media&token=66744153-252a-453d-8296-17c584f30422",
        des: "A boxing movie.",
    },
    {
        title: "Blue Steel",
        releaseYear: 1934,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Blue_steel%201934.jpg?alt=media&token=7146bbb2-9674-4d39-b8f4-be1063670b43",
        des: "When Sheriff Jake Withers (George Hayes) sees John Carruthers (John Wayne) at the safe and then finds the payroll gone, he trails him. Just as he is about to arrest him, John saves his life. Still suspicious, he joins up with the man and later they learn that Melgrove (Edward Peil Sr.), the towns leading citizen, is trying to take over the area's ranches by having his gang stop all incoming supply wagons. Almost all the Lone Star John Wayne movies have one or two quite unusual and memorable scenes. Here, it is the bizarre opening scene. It takes place in a hotel room on a rainy night and it is hard to tell what is going on for most of the scene.",
    },
    {
        title: "The brain that wouldn't die",
        releaseYear: 1962,
        genreId: 5,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Brainthatwouldntdie%201962.jpg?alt=media&token=470ead3a-fd0a-4ffb-a30e-a8b29c52b05a",
        des: "A doctor experimenting with transplant techniques keeps his girlfriend's head alive when she is decapitated in a car crash, then goes hunting for a new body",
    },
    {
        title: "Carnival of Souls",
        releaseYear: 1962,
        genreId: 5,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Carnival_of_Souls%201962.jpg?alt=media&token=fe07b9ca-64bb-4d8a-9529-629b89cef566",
        des: "Atmospheric 60s B-horror film with a cult following. Mary Henry is enjoying the day by riding around with two friends but everything goes wrong when challenged to a drag race and their car gets forced off of a bridge. The car sinks into the murky depths, and all three women are assumed drowned. Some time later Mary emerges unscathed from the river. She tries to start a new life by becoming a church organist but Mary finds herself haunted by a ghostly figure that instills fear and dread into her.",
    },
    {
        title: "The corpse vanishes",
        releaseYear: 1942,
        genreId: 5,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Corpsevanishes%201942.jpg?alt=media&token=d6c9c395-437b-4c8a-8ee7-d7fbb8495265",
        des: "A newspaper reporter begins to investigate after a series of brides die suddenly during their wedding. Her quest leads her to the secret of eternal youth and almost gets her killed.",
    },
    {
        title: "Danger flight",
        releaseYear: 1939,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/DANGER_FLIGHT%201939.jpg?alt=media&token=bd8f1874-0278-417a-b919-9823b4b8f5da",
        des: "Our hero tries to straighten out some juvenile delinquents in this adventure based on the comic strip 'Tailspin Tommy'.",
    },
    {
        title: "Das Cabinet des Dr.Caligari",
        releaseYear: 1920,
        genreId: 5,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Das_Cabinet_des_Dr._Caligari%201920.jpg?alt=media&token=16084a5d-679b-4a4e-b4ca-8feccf16741c",
        des: "The Cabinet of Dr. Caligari is the first modern Horror Film and it influence a number of contemporary productions. A real classic!",
    },
    {
        title: "Detour",
        releaseYear: 1945,
        genreId: 3,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Detour%201945.jpg?alt=media&token=baa28694-0b02-4d93-b3e7-ec6a6ebebef2",
        des: "In flashback, New York nightclub pianist Al Roberts hitchhikes to Hollywood to join his girl Sue. On a rainy night, the sleazy gambler he's riding with mysteriously dies; afraid of the police, Roberts takes the man's identity. But thanks to a blackmailing dame, Roberts' every move plunges him deeper into trouble... ",
    },
    {
        title: "Eternally Yours",
        releaseYear: 1939,
        genreId: 1,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Eternally-Yours%201939.jpg?alt=media&token=e7ef7d54-2215-46b5-ab60-bef969744a80",
        des: "When a magician's act takes precedent over his marriage, his wife gives him trouble. Stars Loretta Young and David Niven.",
    },
    {
        title: "Five minutes to Live",
        releaseYear: 1961,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/FiveMinutesTo_Live%201961.jpg?alt=media&token=338503a0-a0af-4caf-a515-f64ea93aebdf",
        des: "This amazing bank heist movie stars Johnny Cash, Vic Tayback, Ron Howard, and country music great, Merle Travis. Johnny Cash gives a surprising performance as a guitar playing, sadistic psycho-killer. Six year old Ron Howard is absolutely adorable and practically steals the whole show. A must see film.",
    },
    {
        title: "The Goat",
        releaseYear: 1921,
        genreId: 2,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Goat%201921.jpg?alt=media&token=13dac106-58e3-4bb7-b69c-b26876b6b2a3",
        des: "Dumb luck sets some policemen on his trail -- after a series of innovative escapes, he gets mistaken for a murderer with a price on his head, which means the people that aren't chasing him are fleeing from him.",
    },
    {
        title: "Iron mask",
        releaseYear: 1929,
        genreId: 2,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Ironmask%201929.jpg?alt=media&token=fe0df7f6-f577-4782-a3d0-a729633cec2d",
        des: "King Louis XIII of France is thrilled to have born to him a son - an heir to the throne. But when the queen delivers a twin, Cardinal Richelieu sees the second son as a potential for revolution, and has him sent off to Spain to be raised in secret to ensure a peaceful future for France.",
    },
    {
        title: "Marihuana",
        releaseYear: 1936,
        genreId: 5,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Marihuana%201936.jpg?alt=media&token=07c64d45-ccca-4442-9426-5d4888523b36",
        des: "This propaganda film depicting the 'horrors' of marijuana use. A high school girl is led to ruin after befriending a drug dealer who invites her to a party at his beach house.",
    },
    {
        title: "Meet John Doe",
        releaseYear: 1941,
        genreId: 2,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Meet_John_Doe%201941.jpg?alt=media&token=d8bcae6f-efad-4f5b-96e0-d6fbd7e7df7f",
        des: "Directed and produced by Frank Capra, and starring Gary Cooper and Barbara Stanwyck.",
    },
    {
        title: "Mr. Wong Detective",
        releaseYear: 1938,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/MrWongDetective%201938.jpg?alt=media&token=cae2b9a4-a11b-4806-9e0a-cdb30db776df",
        des: "When a chemical manufacturer is killed after asking detective James Wong to help him, Wong investigates this and two subsequent murders. He uncovers a international spy ring hoping to steal the formula for a poison gas being developed by the first victim's company.",
    },
    {
        title: "Nothing Sacred",
        releaseYear: 1946,
        genreId: 1,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Nothing_Sacred%201946.jpg?alt=media&token=22c57fe1-b61e-45fc-ac4e-2176269b5cf2",
        des: "The hotshot newspaper reporter Wallace Cook (Fredric March) tries to get in the good graces of his boss, Oliver Stone (Walter Connolly) by exploiting the 'imminent' death of an ailing young woman, Hazel Flagg (Carole Lombard). By way of newsprint the doomed young lady becomes the toast of New York City until her health situation is revealed as a hoax.",
    },
    {
        title: "Of Human Bondage",
        releaseYear: 1934,
        genreId: 1,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Of_Human_Bondage%201934.jpg?alt=media&token=e8d3cde2-9dd7-46b4-b377-345bb84f8994",
        des: "Nervous about audience reaction to her performance, Davis opted not to attend a preview of the film in Santa Barbara, California, although her mother Ruth and husband Harmon O. Nelson went. Ruth later related, 'For one hour and a half of horrible realism, we sat riveted without speaking a word, with only a fleeting glance now and then at each other.'",
    },
    {
        title: "Oh, Susanna!",
        releaseYear: 1936,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Oh%2C_Susanna!%201936.jpg?alt=media&token=e3b5cc31-2345-480b-80c0-24c80f9fd7a3",
        des: "Directed by Joseph Kane and starring Gene Autry, Smiley Burnette, and Frances Grant. Written by Oliver Drake (filmmaker), the film is about a cowboy who is robbed and then thrown from a train by an escaped murderer who then takes on the cowboy's identity.",
    },
    {
        title: "Svengali",
        genreId: 5,
        releaseYear: 1931,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Svengali%201931.jpg?alt=media&token=860e0c96-46f9-4562-be7e-d71c7bb207c8",
        des: "Sinister music maestro Svengali can control the actions of women through hypnotism and his telepathic powers. When a pupil he has seduced announces she has left her husband for him, he uses his powers to cause her suicide and promptly forgets her.",
    },
    {
        title: "Teenagers from outer space",
        releaseYear: 1959,
        genreId: 2,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Teenagersouterspace%201959.jpg?alt=media&token=fd57bacf-91ea-4e7e-9bbc-6a0d613da1c4",
        des: "A young alien (David Love) falls for a pretty teenage Earth girl (Dawn Anderson) and they team up to try to stop the plans of his invading cohorts. NOTE: This is the MPEG2 (and derivative versions).",
    },
    {
        title: "The Front Page",
        releaseYear: 1931,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/The_Front_Page%201931.jpg?alt=media&token=75ad70db-9026-40d3-af3a-9c8f8c5861a0",
        des: "Hildy Johnson (Pat O'Brien), newspaper reporter, is engaged to Peggy Grant and planning to move to New York for a higher paying advertising job. The court press room is full of lame reporters who invent stories as much as write them. All are waiting to cover the hanging of Earl Williams.",
    },
    {
        title: "The Lost World",
        releaseYear: 1925,
        genreId: 2,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/The_Lost_World%201925.jpg?alt=media&token=de7141a8-5c31-4056-b275-2a09c9c6b5e3",
        des: "The first film adaptation of Sir Arthur Conan Doyle's classic novel about a land where prehistoric creatures still roam.",
    },
    {
        title: "The Phantom of the Opera",
        releaseYear: 1925,
        genreId: 1,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/The_Phantom_of_the_Opera%201925.jpg?alt=media&token=c3521f45-01f6-4229-9594-93c24c17e508",
        des: "A mad, disfigured composer seeks love with a lovely young opera singer.",
    },
    {
        title: "The Rink",
        releaseYear: 1916,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/The_Rink%201916.jpg?alt=media&token=13ddd1af-5853-45ff-a866-16ec0e5b2aa3",
        des: "Charlie Chaplin's 58th Film Released Dec. 04 1916 The Rink was Charlie Chaplin's 8th film for Mutual Films. It co-starred Edna Purviance, Eric Campbell, Henry Bergman and Albert Austin. It is best known for showcasing Chaplin's roller skating skills.",
    },
    {
        title: "The Vagabond",
        releaseYear: 1916,
        genreId: 4,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/The_Vagabond%201916.jpg?alt=media&token=f6127254-1830-47cb-9b52-5e7cbe241aef",
        des: "Charlie Chaplins 53rd Film Released July 10 1916 The Vagabond was a silent film by Charlie Chaplin and his third film with Mutual Films.",
    },
    {
        title: "Vampire Bat",
        releaseYear: 1933,
        genreId: 5,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/Vampirebat%201933.jpg?alt=media&token=190b0caa-1081-44b7-a3c2-17c455de4135",
        des: "Starring Lionel Atwill, Fay Wray, Melvyn Douglas, and Dwight Frye.",
    },
    {
        title: "One week",
        releaseYear: 1920,
        genreId: 1,
        poster: "https://firebasestorage.googleapis.com/v0/b/cineflix-b3821.appspot.com/o/one_week%201920.jpg?alt=media&token=cb1a6a98-212c-4484-860a-3dd6b35fba2b",
        des: "Buster and Sybil exit a chapel as newlyweds. Among the gifts is a portable house you easily put together in one week.",
    },
]